### ISSUE TITLE
Impossible to run sample-app: Ld build/Products/Debug-iphonesimulator/TiGoogleSignIn.app/TiGoogleSignIn normal x86_64

### ISSUE THREAD

**Issue by Brianggalvez** [hansemannn/titanium-google-signin#21] opened 2018-04-02 14:20 UTC
When trying to run provided sample-app or adding module to other project the same error appears at building process: 

`Ld build/Products/Debug-iphonesimulator/TiGoogleSignIn.app/TiGoogleSignIn normal x86_64`

[build_iphone.log](https://github.com/hansemannn/titanium-google-signin/files/1868279/build_iphone.log)

**Comment by hansemannn** [comment] 2018-04-02 15:20
Try to add `-framework SafariServices` to the module.xcconfig frameworks. Looks like Google added a new framework dependency lately

**Comment by Brianggalvez** [comment] 2018-04-04 07:07
Seems that there is a duplicate symbols issue with firebase.core module. Following these guides solved the issue: 

[https://stackoverflow.com/questions/41217839/duplicate-symbols-when-integrating-firebase-and-google-sign-in-sdks-manually-wit](duplicate symbols issue SO)

[https://gist.github.com/drekka/87c507fe5265020e7be491216dc79aa8](gist with script)

**Comment by hansemannn** [comment] 2018-04-04 07:16
I do not think that is your issue. The error log says
```
[TRACE]  Undefined symbols for architecture x86_64:
[TRACE]    "_OBJC_CLASS_$_SSReadingList", referenced from:
[TRACE]        objc-class-ref in GoogleSignIn(please_link_SafariServices.framework__a757707182219759ed991fcb438fd284.o)
[TRACE]  ld: symbol(s) not found for architecture x86_64
[TRACE]  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]  ** BUILD FAILED **
```

**Comment by hansemannn** [comment] 2018-04-14 10:56
Have you solved this? @chmiller can you step in and check if the latest version still works for you as well?

**Comment by hansemannn** [comment] 2018-04-15 11:25
Closing as cannot reproduce as I just tried it. But if it was the firebase.core module, you could contribute a hook that detects it and removes it if existing.

**Closed by hansemannn** 2018-04-15 11:25 UTC

**Comment by User712** [comment] 2018-09-18 05:59
I am still facing this issue @hansemannn . Can you help me how to resolve this? Here is my error.

`Ld build/Products/Debug-iphonesimulator/ABC.app/ABC normal x86_64`

If I remove the Google-Signin module it works fine. So I think issue still exist with the latest version as well.

**Comment by jgiunta** [comment] 2019-04-16 13:56
Is there a solution for these bug ?
